finishline:
  location: world, -303.275, 77.200, -60.437
  lines:
  - '&b&lFinish &d&lLine'
start:
  location: world, -303.640, 77.263, 415.690
  lines:
  - '&8&lS&f&lt&8&la&f&lr&8&lt'
results:
  location: world, -303.422, 79.299, 418.699
  lines:
  - '&5&lTime`s'
powers:
  location: world, -392.669, 87.200, 33.246
  lines:
  - '&0&lP&4&lo&0&lw&4&le&0&lr&4&ls'
