NotifySilentChest: true
NotifyAnyChest: true
config-version: 3
notify:
  any-chest: true
  silent-chest: true
items: {}
toggles:
  items: {}
  silent-chest:
    87fb3c6c-5ff6-4bf6-b326-992c6137ea12: false
  any-chest:
    713cae7a-ef6d-4a06-8922-4741459c12bc: false
settings:
  disable-saving: false
