AddBountyPerKill: 2000
PayForMobKills: false
MobKillMessages: true
BountyLevel:
  Rebel: 1000
  Criminal: 2500
  Bandit: 5000
  Rogue: 10000
  Ruffian: 25000
  Thug: 50000
  Outlaw: 100000
  Hitman: 175000
  Mafiaboss: 300000
  Godfather: 1000000
MobMoney:
  Chicken: 0.5
  Pig: 0.5
  Cow: 0.5
  Sheep: 0.5
  Creeper: 1
  Skeleton: 0.2
  Zombie: 0.2
  Enderman: 1
  Spider: 0.2
  Bat: 2
  Blaze: 0.5
  CaveSpider: 0.2
  ChestedHorse: 0.5
  Donkey: 0.5
  ElderGuardian: 500
  EnderDragon: 500
  Endermite: 0.5
  Ghast: 0.5
  Giant: 50
  Guardian: 20
  Horse: 0.5
  IronGolem: 0.5
  Llama: 0.5
  MagmaCube: 0.5
  Mule: 0.5
  MushroomCow: 0.5
  Ocelot: 0.5
  PigZombie: 2
  PolarBear: 0.5
  Rabbit: 0.5
  Silverfish: 0.5
  SkeletonHorse: 0.5
  Slime: 0.5
  Snowman: 0.5
  Squid: 0.5
  Witch: 1
  Wither: 500
  WitherSkeleton: 2
  Wolf: 0.5
  ZombieHorse: 0.5
  ZombieVillager: 0.5
Bounty:
  zargon_king: 0
  nightghost2: 0
  spyjay_yt: 6000
  melonketchum: 0
  umbyy: 0
  spid0207: 2000
  hotchilliz: 0
  bloodcorn: 0
  maydayparker: 0
  demonisef: 10000
  regner_21: 0
  moosei: 0
  sykaos: 0
  andreimcu: 0
  solvinq: 0
  _wonderbat_: 0
  thatcraftlife: 4000
  agent__cj: 0
  moomoothepirate: 0
  orcgraid: 0
  night_hawkgamer: 0
  spidermanmcu: 0
LastKilled:
  spyjay_yt:
    nightghost2: 04/10/17
    zargon_king: 04/10/17
    umbyy: 04/10/17
  umbyy:
    zargon_king: 04/10/17
  zargon_king:
    regner_21: 04/11/17
    spid0207: 04/12/17
    zargon_king: 04/12/17
  spid0207:
    demonisef: 04/11/17
    umbyy: 04/12/17
    orcgraid: 04/12/17
  demonisef:
    spid0207: 04/12/17
    zargon_king: 04/12/17
