AddBountyPerKill: 2000
PayForMobKills: 'true'
MobKillMessages: true
BountyLevel:
  Rebel: 1000
  Pettycriminal: 2500
  Bandit: 5000
  Rogue: 10000
  Ruffian: 25000
  Thug: 50000
  Outlaw: 100000
  Hitman: 175000
  Mafiaboss: 300000
  Godfather: 1000000
MobMoney:
  Chicken: 2
  Pig: 2
  Cow: 2
  Sheep: 2
  Creeper: 2
  Skeleton: 1
  Zombie: 1
  Enderman: 2
  Spider: 1
  Bat: 5
  Blaze: 2
  CaveSpider: 1
  ChestedHorse: 5
  Donkey: 5
  ElderGuardian: 500
  EnderDragon: 500
  Endermite: 2
  Ghast: 2
  Giant: 100
  Guardian: 50
  Horse: 5
  IronGolem: 5
  Llama: 2
  MagmaCube: 2
  Mule: 5
  MushroomCow: 5
  Ocelot: 5
  PigZombie: 10
  PolarBear: 5
  Rabbit: 5
  Silverfish: 5
  SkeletonHorse: 5
  Slime: 5
  Snowman: 5
  Squid: 5
  Witch: 10
  Wither: 500
  WitherSkeleton: 10
  Wolf: 5
  ZombieHorse: 5
  ZombieVillager: 5
Bounty:
  zargon_king: 0
  nightghost2: 0
  spyjay_yt: 6000
  melonketchum: 0
  umbyy: 0
  spid0207: 2000
  hotchilliz: 0
  bloodcorn: 0
  maydayparker: 0
  demonisef: 10000
  regner_21: 0
  moosei: 0
  sykaos: 0
  andreimcu: 0
  solvinq: 0
  _wonderbat_: 0
  thatcraftlife: 4000
  agent__cj: 0
  moomoothepirate: 0
  orcgraid: 0
  night_hawkgamer: 0
  spidermanmcu: 0
LastKilled:
  spyjay_yt:
    nightghost2: 04/10/17
    zargon_king: 04/10/17
    umbyy: 04/10/17
  umbyy:
    zargon_king: 04/10/17
  zargon_king:
    regner_21: 04/11/17
    spid0207: 04/12/17
    zargon_king: 04/12/17
  spid0207:
    demonisef: 04/11/17
    umbyy: 04/12/17
    orcgraid: 04/12/17
  demonisef:
    spid0207: 04/12/17
    zargon_king: 04/12/17
