AddBountyPerKill: 2000
PayForMobKills: true
MobKillMessages: true
BountyLevel:
  rebel: 1000
  pettycriminal: 2500
  bandit: 5000
  rogue: 10000
  ruffian: 25000
  thug: 50000
  outlaw: 100000
  hitman: 175000
  mafiaboss: 300000
MobMoney:
  Chicken: 0.5
  Pig: 0.5
  Cow: 0.5
  Sheep: 0.5
  Creeper: 1
  Skeleton: 0.2
  Zombie: 0.2
  Enderman: 0.5
  Spider: 0.2
  Bat: 0.8
  Blaze: 0.2
  CaveSpider: 0.2
  ChestedHorse: 0.5
  Donkey: 0.5
  ElderGuardian: 500
  EnderDragon: 500
  Endermite: 0.5
  Ghast: 0.5
  Giant: 250
  Guardian: 50
  Horse: 0.5
  IronGolem: 0.5
  Llama: 0.5
  MagmaCube: 0.5
  Mule: 0.5
  MushroomCow: 0.5
  Ocelot: 0.5
  PigZombie: 0.5
  PolarBear: 0.5
  Rabbit: 0.5
  Silverfish: 0.5
  SkeletonHorse: 0.5
  Slime: 0.5
  Snowman: 0.5
  Squid: 0.5
  Witch: 2
  Wither: 500
  WitherSkeleton: 10
  Wolf: 0.5
  ZombieHorse: 0.5
  ZombieVillager: 0.5
Bounty:
  zargon_king: 0
  nightghost2: 0
  spyjay_yt: 0
  melonketchum: 0
  umbyy: 0
  spid0207: 0
  hotchilliz: 0
  bloodcorn: 0
  maydayparker: 0
  demonisef: 0
  regner_21: 0
  moosei: 0
  sykaos: 0
  andreimcu: 0
  solvinq: 0
  _wonderbat_: 0
  thatcraftlife: 0
  agent__cj: 0
  moomoothepirate: 0
LastKilled:
  spyjay_yt:
    nightghost2: 04/10/17
    zargon_king: 04/10/17
    umbyy: 04/10/17
  umbyy:
    zargon_king: 04/10/17
