WorldEvents:
  FullMoon:
    Enabled: true
    Factor: 3.0
    Message: A full moon is rising, empowering waterbending like never before.
  LunarEclipse:
    Enabled: true
    Frequency: 40
    Message: A lunar eclipse is out! Waterbenders are temporarily powerless.
  SolarEclipse:
    Enabled: true
    Frequency: 20
    Message: A solar eclipse is out! Firebenders are temporarily powerless.
  SozinsComet:
    Enabled: true
    Frequency: 100
    Factor: 5.0
    Message: Sozin's Comet is passing overhead! Firebending is now at its most powerful.
    EndMessage: Sozin's Comet has passed.
Abilities:
  AvatarStateOnFinalBlow: true
ElementAssign:
  Enabled: true
  Default: None
  Percentages:
    Earth: 0.205
    Water: 0.205
    Air: 0.205
    Fire: 0.205
    Chi: 0.18
SubElementAssign:
  Enabled: true
  Percentages:
    Blood: 0.01
    Combustion: 0.3
    Flight: 0.01
    Healing: 0.2
    Ice: 1
    Lava: 0.3
    Lightning: 0.5
    Metal: 0.7
    Plant: 0.7
    Sand: 1
    SpiritualProjection: 0.4
Storage:
  engine: sqlite
  MySQL:
    host: localhost
    port: 3306
    pass: ''
    db: minecraft
    user: root
